/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qTeslaTestJNI */

#ifndef _Included_qTeslaTestJNI
#define _Included_qTeslaTestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qTeslaTestJNI
 * Method:    checkQTesla
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_qTeslaTestJNI_checkQTesla
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     qTeslaTestJNI
 * Method:    cryptoSignKeyPair
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_qTeslaTestJNI_cryptoSignKeyPair
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     qTeslaTestJNI
 * Method:    cryptoSign
 * Signature: ([BJ[BJ[B)I
 */
JNIEXPORT jint JNICALL Java_qTeslaTestJNI_cryptoSign
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     qTeslaTestJNI
 * Method:    cryptoVerify
 * Signature: ([BJ[BJ[B)I
 */
JNIEXPORT jint JNICALL Java_qTeslaTestJNI_cryptoVerify
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     qTeslaTestJNI
 * Method:    getPrivateKeySize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_qTeslaTestJNI_getPrivateKeySize
  (JNIEnv *, jobject);

/*
 * Class:     qTeslaTestJNI
 * Method:    getPublicKeySize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_qTeslaTestJNI_getPublicKeySize
  (JNIEnv *, jobject);

/*
 * Class:     qTeslaTestJNI
 * Method:    getSigatureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_qTeslaTestJNI_getSigatureSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
