/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI */

#ifndef _Included_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
#define _Included_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
 * Method:    checkQTesla
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI_checkQTesla
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
 * Method:    cryptoSignKeyPair
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI_cryptoSignKeyPair
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
 * Method:    cryptoSign
 * Signature: ([BJ[BJ[B)I
 */
JNIEXPORT jint JNICALL Java_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI_cryptoSign
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray, jint nt);

/*
 * Class:     sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
 * Method:    cryptoVerify
 * Signature: ([BJ[BJ[B)I
 */
JNIEXPORT jint JNICALL Java_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI_cryptoVerify
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
 * Method:    getPrivateKeySize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI_getPrivateKeySize
  (JNIEnv *, jobject);

/*
 * Class:     sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
 * Method:    getPublicKeySize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI_getPublicKeySize
  (JNIEnv *, jobject);

/*
 * Class:     sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI
 * Method:    getSigatureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sctudarmstadt_qtesla_cwrapper_qTeslaTestJNI_getSignatureSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
